//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdskTemplateMepTools.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdskTemplateMepTools.Resources.Localization.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нумерация.
        /// </summary>
        public static string AutonumerateButtonName {
            get {
                return ResourceManager.GetString("AutonumerateButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение параметра ADSK_Позиция.
        /// </summary>
        public static string AutonumerateTootip {
            get {
                return ResourceManager.GetString("AutonumerateTootip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить        ///семейства.
        /// </summary>
        public static string CheckAdskButtonName {
            get {
                return ResourceManager.GetString("CheckAdskButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка файлов семейств на соответствие требованиям по общим параметрам ADSK.
        /// </summary>
        public static string CheckAdskTooltip {
            get {
                return ResourceManager.GetString("CheckAdskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать        ///значения.
        /// </summary>
        public static string CopyAdskButtonName {
            get {
                return ResourceManager.GetString("CopyAdskButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка        ///копирования.
        /// </summary>
        public static string CopyAdskSettingsButtonName {
            get {
                return ResourceManager.GetString("CopyAdskSettingsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка параметров копирования.
        /// </summary>
        public static string CopyAdskSettingsTooltip {
            get {
                return ResourceManager.GetString("CopyAdskSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение параметров ADSK.
        /// </summary>
        public static string CopyAdskTooltip {
            get {
                return ResourceManager.GetString("CopyAdskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать        ///пространства.
        /// </summary>
        public static string CreateSpacesButtonName {
            get {
                return ResourceManager.GetString("CreateSpacesButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание и автоматическое копирования значений параметров из архитектурных помещений в инженерные пространства. Используется экземпляр размещенной связи АР.
        /// </summary>
        public static string CreateSpacesTooltip {
            get {
                return ResourceManager.GetString("CreateSpacesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать системы        ///воздуховодов.
        /// </summary>
        public static string DuctSystemButtonName {
            get {
                return ResourceManager.GetString("DuctSystemButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дублирования значений Имя системы для воздушных систем в проекте. Создание копий видов с фильтрами для данных систем.
        /// </summary>
        public static string DuctSystemTooltip {
            get {
                return ResourceManager.GetString("DuctSystemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматиция шаблона ADSK.
        /// </summary>
        public static string PanelName {
            get {
                return ResourceManager.GetString("PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать системы        ///трубопроводов.
        /// </summary>
        public static string PipeSystemButtonName {
            get {
                return ResourceManager.GetString("PipeSystemButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дублирования значений Имя системы для трубопроводных систем в проекте. Создание копий видов с фильтрами для данных систем.
        /// </summary>
        public static string PipeSystemTooltip {
            get {
                return ResourceManager.GetString("PipeSystemTooltip", resourceCulture);
            }
        }
    }
}
